### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by msafronov** [jmquigley/util.chdir#1]
i set root permissions to repo folder:
`$ sudo chown -R root:root ./util.chdir`

run test as non-root user:
`npm test`

how about permissions? )
`before Error: EACCES: permission denied, mkdir 'tmp-unit-test-data'`

**Comment by jmquigley** [comment]
The unit test creates that directory to setup a fake tree for testing.  It cleans it up when the test finishes.  Let me find a better location than the cwd() for the tests (that is portable).
